filter:
  proximity_power_line:
    enabled: false
    max_distance_km: 20.0
  proximity_water_source:
    enabled: false
    max_distance_km: 1.0
  proximity_substation:
    enabled: true
    max_distance_km: 30.0

pipeline:
  max_locations: 999999
